#.github/workflows/dotnet.yml
name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Add NuGet.org source (if not already added)
      run: |
        if (-not (dotnet nuget list source | Select-String -Pattern 'nuget.org')) {
          dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
        }

    - name: Restore dependencies
      run: |
        dotnet restore "Lab5 - Elijah Mckeehan/Lab5 - Elijah Mckeehan.csproj" --source https://api.nuget.org/v3/index.json
        dotnet restore "Lab 6 - Tests/Lab 6 - Tests.csproj" --source https://api.nuget.org/v3/index.json

    - name: Build projects
      run: |
        dotnet build "Lab5 - Elijah Mckeehan/Lab5 - Elijah Mckeehan.csproj" --no-restore
        dotnet build "Lab 6 - Tests/Lab 6 - Tests.csproj" --no-restore

    - name: Run tests
      run: |
        dotnet test "Lab 6 - Tests/Lab 6 - Tests.csproj" --no-build --verbosity normal
    
